In [1]:
pip install gensim

In [2]:
import gensim

In [3]:
from gensim.models import Word2Vec,KeyedVectors

In [4]:
import gensim.downloader as api

In [5]:
wv = api.load('word2vec-google-news-300')
vec_king = wv['king']

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [6]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

So we can find Similiarity b/w words

In [7]:
wv.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [8]:
wv.most_similar('happy')

[('glad', 0.7408890724182129),
 ('pleased', 0.6632170677185059),
 ('ecstatic', 0.6626912355422974),
 ('overjoyed', 0.6599286794662476),
 ('thrilled', 0.6514049172401428),
 ('satisfied', 0.6437949538230896),
 ('proud', 0.636042058467865),
 ('delighted', 0.627237856388092),
 ('disappointed', 0.6269949674606323),
 ('excited', 0.6247665286064148)]

In [9]:
wv.similarity("cricket","sports")

0.40087253

In [15]:
wv.similarity("king","queen")

0.6510957

In [10]:
wv.similarity("football","sports")

0.5927178

In [16]:
wv.most_similar(positive=['king', 'woman'], negative=['man'])

[('queen', 0.7118193507194519),
 ('monarch', 0.6189674139022827),
 ('princess', 0.5902431011199951),
 ('crown_prince', 0.5499460697174072),
 ('prince', 0.5377321839332581),
 ('kings', 0.5236844420433044),
 ('Queen_Consort', 0.5235945582389832),
 ('queens', 0.5181134343147278),
 ('sultan', 0.5098593831062317),
 ('monarchy', 0.5087411999702454)]

In [11]:
vec = wv["king"] - wv["man"] + wv["women"]

In [12]:
vec

array([-0.33984375,  0.06298828, -0.00994873,  0.3305664 ,  0.10327148,
       -0.25854492,  0.19677734, -0.32476807, -0.15917969,  0.45752716,
       -0.39208984, -0.22460938,  0.02929688,  0.31982422, -0.0958252 ,
       -0.05932617,  0.01855469, -0.03945923,  0.01101685,  0.33984375,
        0.10351562,  0.14396667, -0.07641602,  0.06640625, -0.10839844,
       -0.1953125 , -0.3564453 , -0.02124023, -0.16503906, -0.16247559,
       -0.05519104, -0.1003418 ,  0.01464844,  0.23449707, -0.26611328,
       -0.07080078, -0.26904297, -0.00292969, -0.06738281, -0.02050781,
        0.04418945, -0.09326172,  0.12304688,  0.10626221,  0.10290527,
        0.01660156, -0.10791016, -0.0065918 ,  0.17578125,  0.10028076,
        0.22363281, -0.05761719, -0.31743622,  0.3922119 , -0.35498047,
       -0.23643494, -0.01074219, -0.01334572, -0.15283203, -0.00793457,
        0.08203125,  0.09985352,  0.003479  ,  0.11608887,  0.14550781,
       -0.125     , -0.11254883,  0.2548828 , -0.04345703,  0.34

In [13]:
wv.most_similar([vec])

[('king', 0.6478992700576782),
 ('queen', 0.535493791103363),
 ('women', 0.5233659148216248),
 ('kings', 0.5162314772605896),
 ('queens', 0.4995364248752594),
 ('kumaris', 0.49238473176956177),
 ('princes', 0.46233269572257996),
 ('monarch', 0.45280295610427856),
 ('monarchy', 0.4293173849582672),
 ('kings_princes', 0.42342400550842285)]

In [17]:
odd_one_out = wv.doesnt_match(['breakfast', 'cereal', 'dinner', 'lunch'])

In [18]:
odd_one_out

'cereal'

In [22]:
len(wv.key_to_index)

3000000

In [23]:
list(wv.index_to_key)

['</s>',
 'in',
 'for',
 'that',
 'is',
 'on',
 '##',
 'The',
 'with',
 'said',
 'was',
 'the',
 'at',
 'not',
 'as',
 'it',
 'be',
 'from',
 'by',
 'are',
 'I',
 'have',
 'he',
 'will',
 'has',
 '####',
 'his',
 'an',
 'this',
 'or',
 'their',
 'who',
 'they',
 'but',
 '$',
 'had',
 'year',
 'were',
 'we',
 'more',
 '###',
 'up',
 'been',
 'you',
 'its',
 'one',
 'about',
 'would',
 'which',
 'out',
 'can',
 'It',
 'all',
 'also',
 'two',
 'after',
 'first',
 'He',
 'do',
 'time',
 'than',
 'when',
 'We',
 'over',
 'last',
 'new',
 'other',
 'her',
 'people',
 'into',
 'In',
 'our',
 'there',
 'A',
 'she',
 'could',
 'just',
 'years',
 'some',
 'U.S.',
 'three',
 'million',
 'them',
 'what',
 'But',
 'so',
 'no',
 'like',
 'if',
 'only',
 'percent',
 'get',
 'did',
 'him',
 'game',
 'back',
 'because',
 'now',
 '#.#',
 'before',
 'company',
 'any',
 'team',
 'against',
 'off',
 'This',
 'most',
 'made',
 'through',
 'make',
 'second',
 'state',
 'well',
 'day',
 'season',
 'says',
 'w

In [26]:
wv.similarity('easy','below')

0.03273055

In [29]:
wv.most_similar('king', topn=10)


[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('Prince_Paras', 0.5432944297790527),
 ('throne', 0.5422105193138123)]

In [30]:
wv.get_vector('king', norm=True)

array([ 4.34063822e-02,  1.02627501e-02,  2.96526169e-03,  4.81171533e-02,
       -8.83269403e-03, -1.24498932e-02,  3.85273732e-02, -6.83061704e-02,
        1.76653881e-02,  1.25171900e-01, -8.34479332e-02, -1.04309916e-01,
       -6.12400137e-02, -8.58033169e-03, -5.78751788e-02, -5.85481450e-02,
        1.19451676e-02,  1.79808424e-03,  1.59829706e-02,  4.44158353e-02,
        4.71077040e-02,  3.88638563e-02,  2.05255002e-02,  4.71077040e-02,
        3.48260514e-02, -6.09035306e-02, -8.68127644e-02,  2.06096210e-02,
        1.17769256e-01, -1.07254144e-02,  3.60037461e-02,  2.12825872e-02,
        4.29016575e-02,  1.37958273e-01, -1.11039586e-01,  2.89375894e-02,
        1.34593435e-02,  2.01890152e-03,  2.42268182e-02,  5.95575981e-02,
        4.77806702e-02, -7.97466114e-02,  9.75802392e-02,  4.91266064e-02,
        1.17769256e-01, -8.24384764e-03, -3.78544033e-02,  1.14404419e-02,
       -1.88430808e-02,  5.27858641e-03, -5.58562763e-02,  5.45103438e-02,
       -8.95046368e-02,  

In [31]:
similarity = wv.cosine_similarities(wv['king'], [wv['queen'], wv['man']])

In [32]:
print(f"Cosine similarity between 'king' and 'queen': {similarity[0]}")

Cosine similarity between 'king' and 'queen': 0.6510956287384033


In [33]:
print(f"Cosine similarity between 'king' and 'man': {similarity[1]}")

Cosine similarity between 'king' and 'man': 0.22942668199539185


In [36]:
words = ['king', 'queen', 'man', 'woman']
similarity_matrix = [[wv.similarity(w1, w2) for w2 in words] for w1 in words]
print(f"Similarity matrix:\n{similarity_matrix}")


Similarity matrix:
[[1.0, 0.6510957, 0.22942673, 0.12847973], [0.6510957, 1.0, 0.16658202, 0.31618136], [0.22942673, 0.16658202, 1.0, 0.76640123], [0.12847973, 0.31618136, 0.76640123, 1.0]]


In [37]:
from numpy import dot
from numpy.linalg import norm

def most_similar_matrix(wv, word):
    vec = wv[word]
    sims = dot(wv.vectors, vec) / (norm(wv.vectors, axis=1) * norm(vec))
    return sorted([(s, wv.index_to_key[i]) for i, s in enumerate(sims)], reverse=True)

similar_matrix = most_similar_matrix(wv, 'king')
print(f"Most similar words to 'king' using similarity matrix:\n{similar_matrix[:10]}")


Most similar words to 'king' using similarity matrix:
[(1.0000001, 'king'), (0.71380454, 'kings'), (0.6510956, 'queen'), (0.64131945, 'monarch'), (0.62042195, 'crown_prince'), (0.61599934, 'prince'), (0.5864824, 'sultan'), (0.5797567, 'ruler'), (0.56465524, 'princes'), (0.5432944, 'Prince_Paras')]
